@host=https://localhost:7048
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Wolfgang",
    "lastName": "Gogo",
    "email": "Wolfgang.Goritschnig@mailme.to",
    "password": "Uncrackable"
}
